# -*- coding: utf-8 -*-
"""NLP_Pratical 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riUQ-2FtO-dvLYrHqF5tSUHOEesbKTqN
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')

sentence="Natural Language Processing helps computers understand human language"

#tokenization
tokens=word_tokenize(sentence)

# pos tags
nltk.download('averaged_perceptron_tagger_eng')
tags=pos_tag(tokens)
print("POS Tags:", tags)